{% set version = "1.8-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-asbio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/asbio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/asbio/asbio_{{ version }}.tar.gz
  sha256: bd68812077bcd51ad80b4c2a33635644e326f3a835d81da570ad5be6e67310dc

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-combinat
    - r-desolve
    - r-gwidgets2
    - r-gwidgets2tcltk
    - r-lattice
    - r-multcompview
    - r-mvtnorm
    - r-pixmap
    - r-plotrix
    - r-scatterplot3d
    - r-tkrplot
  run:
    - r-base
    - r-combinat
    - r-desolve
    - r-gwidgets2
    - r-gwidgets2tcltk
    - r-lattice
    - r-multcompview
    - r-mvtnorm
    - r-pixmap
    - r-plotrix
    - r-scatterplot3d
    - r-tkrplot

test:
  commands:
    - $R -e "library('asbio')"           # [not win]
    - "\"%R%\" -e \"library('asbio')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=asbio
  license: GPL-2.0-or-later
  summary: 'Contains functions from: Aho, K. (2014) Foundational and Applied Statistics for Biologists using R.  CRC/Taylor and Francis, Boca Raton, FL, ISBN: 978-1-4398-7338-0.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: asbio
# Type: Package
# Title: A Collection of Statistical Tools for Biologists
# Version: 1.5-5
# Depends: R (>= 2.15.1), tcltk
# Imports: scatterplot3d, pixmap, plotrix, mvtnorm, deSolve, lattice, multcompView, grDevices, graphics, stats, utils
# Suggests: akima, boot
# Date: 2019-1-23
# SystemRequirements: BWidget
# Author: Ken Aho
# Maintainer: Ken Aho <kenaho1@gmail.com>
# Description: Contains functions from: Aho, K. (2014) Foundational and Applied Statistics for Biologists using R.  CRC/Taylor and Francis, Boca Raton, FL, ISBN: 978-1-4398-7338-0.
# License: GPL (>= 2)
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2019-01-23 21:14:02 UTC; Ken Aho
# Repository: CRAN
# Date/Publication: 2019-01-23 22:10:03 UTC
